language: objective-c
osx_image: xcode8
branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
  - set -o pipefail
  - xcodebuild -project BluetoothKit.xcodeproj -scheme "BluetoothKit iOS" -sdk iphonesimulator
    -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO
  - pod lib lint --quick
